---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: jenkinsagent
  name: jenkinsagent
  namespace: jenkins
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: jenkinsagent
  template:
    metadata:
      labels:
        k8s-app: jenkinsagent
      namespace: devops
      name: jenkinsagent
    spec:
      hostAliases:
        - ip: "192.168.45.21"
          hostnames:
            - "gitlab.idevops.site"
        - ip: "192.168.45.21"
          hostnames:
            - "sonar.idevops.site"
        - ip: "192.168.45.21"
          hostnames:
            - "nexus.idevops.site"
      containers:
        - name: jenkinsagent
          #image: ccr.ccs.tencentyun.com/devopsvip/inbound-agent:latest-jdk11
          image: ccr.ccs.tencentyun.com/devopsvip/custom-build-agent:v2
          securityContext:
            privileged: true
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 4000m
              memory: 8Gi
            requests:
              cpu: 500m
              memory: 512Mi
          env:
            - name: JENKINS_URL
              value: http://jenkins.jenkins.svc.cluster.local:8080
            - name: JENKINS_SECRET
              value: ab642038369e0180b2116627bc60a9b81b811893f40f0d4a9ed4cb9cb232e3bb
            - name: JENKINS_AGENT_NAME
              value: build
            - name: JENKINS_AGENT_WORKDIR
              value: /home/jenkins/workspace
          volumeMounts:
            - name: jenkins-build-cache
              mountPath: /home/jenkins/jenkins-build-cache
            - name: jenkins-workspace
              mountPath: /home/jenkins/workspace
      volumes:
        - name: jenkins-build-cache
          persistentVolumeClaim:
            claimName: jenkins-build-cache
        - name: jenkins-workspace
          persistentVolumeClaim:
            claimName: jenkins-workspace